AWSTemplateFormatVersion: 2010-09-09
Description: Launch Lambda function product from SC
Parameters:
  RoleName:
    Type: String
  LambdaName:
    Type: String
  ContainerImageUri:
    Type: String

  ### API Gateway
  APIName:
    Type: String
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Code:
        ImageUri: !Ref ContainerImageUri
      Role: !GetAtt LambdaRole.Arn
      FunctionName: !Ref LambdaName

  LambdaLogging:
    Type: AWS::Logs::LogGroup
    DependsOn: LambdaFunction
    Properties:
      LogGroupName: !Join [/, ["/aws/lambda", !Ref LambdaFunction]]
      RetentionInDays: 1

  APIGateway:
    Type: AWS::ApiGatewayV2::Api
    DependsOn: LambdaFunction
    Properties:
      Name: !Ref APIName
      ProtocolType: "HTTP"

  APIGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    DependsOn: APIGateway
    Properties:
      ApiId: !Ref APIGateway
      StageName: "$default"
      AutoDeploy: true

  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    DependsOn: APIGateway
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*

  APIGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    DependsOn: APIGateway
    Properties:
      ApiId: !Ref APIGateway
      IntegrationMethod: "POST"
      IntegrationType: "AWS_PROXY"
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: "2.0"

  APIGatewayRoute:
    Type: AWS::ApiGatewayV2::Route
    DependsOn: APIGatewayIntegration
    Properties:
      ApiId: !Ref APIGateway
      RouteKey: !Sub "POST /sinkdrain"
      Target: !Join
        - /
        - - integrations
          - !Ref APIGatewayIntegration
